"""Core types: enums, errors, fixed messages, source records, and results."""

from __future__ import annotations

from camera_count.core.enums import (
    TRUSTED_STATUSES,
    CitationKind,
    CountType,
    MethodType,
    Protocol,
    VerificationStatus,
)
from camera_count.core.errors import (
    CameraCountError,
    DeviceAccessError,
    ForbiddenConstructionError,
    ForbiddenOperationError,
    MetadataError,
    ParseError,
    ProtocolError,
    RegistryError,
    ToolNotFoundError,
    UnknownSourceError,
    UnverifiedSourceError,
    ValueOutOfBoundsError,
)
from camera_count.core.models import (
    UINT32_MAX,
    CameraIdentity,
    CounterSlot,
    CountResult,
    NonAuthoritativeCounter,
    ShutterReading,
    Unavailable,
    build_counter_slots,
    first_reading,
    validate_count_value,
)
from camera_count.core.sources import (
    Citation,
    SourceRecord,
    SourceResolver,
    get_source_resolver,
    resolve_source,
    set_source_resolver,
)

__all__ = [
    "TRUSTED_STATUSES",
    "UINT32_MAX",
    "CameraCountError",
    "CameraIdentity",
    "Citation",
    "CitationKind",
    "CountResult",
    "CountType",
    "CounterSlot",
    "DeviceAccessError",
    "ForbiddenConstructionError",
    "ForbiddenOperationError",
    "MetadataError",
    "MethodType",
    "NonAuthoritativeCounter",
    "ParseError",
    "Protocol",
    "ProtocolError",
    "RegistryError",
    "ShutterReading",
    "SourceRecord",
    "SourceResolver",
    "ToolNotFoundError",
    "Unavailable",
    "UnknownSourceError",
    "UnverifiedSourceError",
    "ValueOutOfBoundsError",
    "VerificationStatus",
    "build_counter_slots",
    "first_reading",
    "get_source_resolver",
    "resolve_source",
    "set_source_resolver",
    "validate_count_value",
]
