"""Generate THIRD_PARTY_LICENSES.md from the installed environment.

Distributing other people's work means saying whose it is and under what terms.
This reads the metadata of what is actually installed rather than a hand-kept
list, so it cannot quietly go stale.

Components that are not Python packages - ExifTool, and the Qt libraries inside
PySide6 - are recorded explicitly, because no package metadata describes them
the way a reader needs.
"""

from __future__ import annotations

from importlib import metadata
from pathlib import Path
from typing import Final

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
OUTPUT: Final = REPO_ROOT / "THIRD_PARTY_LICENSES.md"

#: Packages that end up in a release. Development-only tools are not shipped.
SHIPPED: Final[tuple[str, ...]] = (
    "typer",
    "click",
    "PyYAML",
    "jsonschema",
    "jsonschema-specifications",
    "referencing",
    "rpds-py",
    "attrs",
    "platformdirs",
    "comtypes",
    "PySide6-Essentials",
    "shiboken6",
    "typing-extensions",
    "rich",
    "markdown-it-py",
    "mdurl",
    "Pygments",
    "pyusb",
    "libusb-package",
)

HEADER: Final = """# Third-party licences

<!-- Generated by scripts/generate_third_party_licenses.py. Do not edit by hand. -->

Camera Count Tool is licensed under Apache-2.0 (see [LICENSE](LICENSE)). It is
distributed with, or depends on, the components below. Their licences are their
own and apply to their own code.

"""

NON_PYTHON: Final = """
## Components that are not Python packages

### ExifTool

Copyright Phil Harvey. Distributed under the same terms as Perl itself, which
is a choice of the GNU General Public License or the Artistic License.

Packaged releases bundle the official self-contained Windows build, which
includes a Perl interpreter. It is shipped **unmodified** and is executed as a
separate process; no ExifTool code is linked into this program. The archive is
verified against the SHA-256 published on exiftool.org before it is used - see
`scripts/fetch_exiftool.py`.

Home page: https://exiftool.org

### Qt (inside PySide6)

Copyright The Qt Company Ltd and contributors. Used under the GNU Lesser
General Public License version 3.

The one-folder distribution keeps the Qt libraries as separate, replaceable
files next to the application rather than linking them statically, so they can
be swapped for other builds of the same version, as the LGPL requires.

Qt for Python licensing: https://doc.qt.io/qtforpython-6/licenses.html

### libusb (optional)

Copyright the libusb contributors. GNU Lesser General Public License v2.1.
Only present when the optional `winusb` extra is installed, and loaded as a
shared library rather than linked.

## Protocol and metadata references

This program contains no code from the projects below. It cites them as the
sources of published protocol constants and metadata field definitions, which
are facts about a format rather than the expression of a program:

- **libgphoto2** - PTP operation, response and data-type codes
  (`camlibs/ptp2/ptp.h`). Used strictly as reference material.
- **ExifTool tag tables** - which MakerNotes field a manufacturer uses for an
  actuation counter, and for which models.
- **Windows SDK headers** - the Windows Portable Devices command and property
  keys (`WpdMtpExtensions.h`, `PortableDevice.h`).
- **linux-usb.org `usb.ids`** - USB vendor identifiers.

Every registry entry names its source and the exact line it came from.
"""


def describe(name: str) -> tuple[str, str, str, str] | None:
    try:
        distribution = metadata.distribution(name)
    except metadata.PackageNotFoundError:
        return None

    info = distribution.metadata
    licence = info.get("License") or ""
    if not licence or licence.strip() in {"UNKNOWN", ""}:
        classifiers = info.get_all("Classifier") or []
        licences = [
            item.split("::")[-1].strip() for item in classifiers if item.startswith("License ::")
        ]
        licence = ", ".join(licences) or "see the project's own distribution"
    licence = " ".join(licence.split())
    if len(licence) > 90:
        licence = licence[:87] + "..."

    url = (
        info.get("Home-page")
        or next(
            (
                value.split(",", 1)[-1].strip()
                for value in (info.get_all("Project-URL") or [])
                if value
            ),
            "",
        )
        or ""
    )
    return distribution.metadata["Name"], distribution.version, licence, url


def main() -> int:
    rows: list[tuple[str, str, str, str]] = []
    missing: list[str] = []
    for name in SHIPPED:
        found = describe(name)
        if found is None:
            missing.append(name)
            continue
        rows.append(found)

    lines = [HEADER, "## Python packages", ""]
    lines.append("| Package | Version | Licence | Home |")
    lines.append("|---|---|---|---|")
    for name, version, licence, url in sorted(rows, key=lambda row: row[0].lower()):
        home = f"[link]({url})" if url.startswith("http") else ""
        lines.append(f"| {name} | {version} | {licence} | {home} |")

    if missing:
        lines.append("")
        lines.append(
            "Not installed in the environment this was generated from, and "
            "therefore not shipped: " + ", ".join(sorted(missing)) + "."
        )

    lines.append(NON_PYTHON)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(rows)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
