"""Generate docs/manufacturer-support.md from the camera registry.

The document is generated so that it cannot drift from the data: CI regenerates
it and fails if the result differs from what is committed.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

from camera_count.registry import load_registry
from camera_count.registry.loader import CameraRegistry
from camera_count.registry.models import CameraModel, ManufacturerEntry

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
OUTPUT: Final = REPO_ROOT / "docs" / "manufacturer-support.md"

HEADER: Final = """# Manufacturer support

<!-- Generated by scripts/generate_support_docs.py. Do not edit by hand. -->

This page is generated from the camera registry
(`src/camera_count/registry/camera_database/`). Every method listed here
carries a citation, and every citation can be checked against the source it
names.

**A model that is not listed reports `EXACT SHUTTER COUNT NOT AVAILABLE`.**
That is the correct result, not a gap to be filled with a guess. If you can
cite a method for a camera that is missing, please
[open an issue](https://github.com/Osama01Anwar/camera-count-tool/issues/new/choose).

## What the statuses mean

| Status | Meaning |
|---|---|
| `documented` | A public source defines this field or operation as the actuation counter for this model. The value is read and reported exactly. |
| `hardware_verified` | As above, and a human has confirmed on a physical body that the count increases by exactly the number of shutter presses made. Requires a row in [hardware-test-matrix.md](hardware-test-matrix.md). |
| `unverified` | Recorded as a lead only. Never produces a displayed number. |

A model listed as `*` means the method is documented in that manufacturer's
main MakerNotes table rather than per model. It is used only when no exact
model entry matches, and it still reports the counter as unavailable when the
field is not present in the file.
"""

COUNTER_LABELS: Final[dict[str, str]] = {
    "mechanical": "Mechanical shutter",
    "electronic": "Electronic shutter",
    "efc": "Electronic first curtain",
    "total_releases": "Total releases",
}


def model_section(model: CameraModel) -> list[str]:
    title = "any model with the documented field" if model.is_wildcard else model.model
    lines = [f"#### {title}", ""]

    if not model.methods:
        lines.append("No method is recorded.")
        lines.append("")
        return lines

    lines.append("| Counter | Method | Identifier | Status | Citation |")
    lines.append("|---|---|---|---|---|")
    for method in model.methods:
        counter = COUNTER_LABELS.get(method.count_type.value, method.count_type.value)
        lines.append(
            f"| {counter} | `{method.method_type.value}` | `{method.identifier}` | "
            f"{method.verification_status.value} | `{method.citation.reference}` |"
        )
    lines.append("")

    for method in model.methods:
        if method.citation.note:
            lines.append(f"- **`{method.identifier}`** - {method.citation.note}")
    if any(method.citation.note for method in model.methods):
        lines.append("")

    if model.limitations:
        lines.append("Limitations:")
        lines.extend(f"- {item}" for item in model.limitations)
        lines.append("")
    return lines


def entry_section(entry: ManufacturerEntry) -> list[str]:
    lines = [f"### {entry.manufacturer}", ""]

    if entry.usb_vendor_ids:
        ids = ", ".join(f"`{vendor.display()}`" for vendor in entry.usb_vendor_ids)
        lines.append(f"USB vendor ids: {ids}")
        lines.append("")

    if entry.notes:
        lines.append(entry.notes)
        lines.append("")

    if not entry.models:
        lines.append("**No model has a documented exact-count method yet.**")
        lines.append("")
        return lines

    for model in entry.models:
        lines.extend(model_section(model))
    return lines


def render(registry: CameraRegistry) -> str:
    documented = [entry for entry in registry.entries if entry.models]
    undocumented = [entry for entry in registry.entries if not entry.models]

    lines = [HEADER, "## Summary", ""]
    lines.append(f"- Manufacturers in the registry: **{len(registry.entries)}**")
    lines.append(f"- Models with a documented method: **{registry.documented_model_count}**")
    lines.append(f"- Manufacturers with no documented method yet: **{len(undocumented)}**")
    lines.append("")

    lines.append("## Manufacturers with a documented method")
    lines.append("")
    for entry in documented:
        lines.extend(entry_section(entry))

    lines.append("## Manufacturers with no documented method yet")
    lines.append("")
    lines.append(
        "These are researched conclusions, not omissions. Each note records what "
        "was searched and when."
    )
    lines.append("")
    for entry in undocumented:
        lines.extend(entry_section(entry))

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    registry = load_registry()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(registry), encoding="utf-8")
    print(f"wrote {OUTPUT} ({registry.documented_model_count} documented models)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
